name: contact_sych
description: A new Flutter project.

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.0

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #contacts_service: ^0.4.6
  #permission_handler: ^5.0.1+1
  gson: ^0.1.4
  shared_preferences: ^2.0.8
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  permission_handler_platform_interface:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
    image_path: "assets/logo.png"
    android: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
 # assets:
    #- assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
